version: '3.8'

services:
  # Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: soceisi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ramos
      MYSQL_DATABASE: inscripciones_db
      MYSQL_USER: ramos
      MYSQL_PASSWORD: Fni71882923
    ports:
      - "3306:3306"
    volumes:
      # Usamos un volumen gestionado por Docker para evitar líos de permisos en NTFS
      - mysql_data:/var/lib/mysql

  # Interfaz Web phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: soceisi_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ramos
    depends_on:
      - db

volumes:
  mysql_data: